Exercises
Within your codeup-data-science directory, create a new directory named classification-exercises. This will be where you do your work for this module. Create a repository on GitHub with the same name, and link your local repository to GitHub. Make sure to add a .gitignore file. In your .gitignore, ignore .DS_Store, .ipynb_checkpoints/, __pycache__, titanic.csv, iris.csv, and env.py. Add and commit your .gitignore file before moving forward.

The end product of this exercise is a jupyter notebook (classification_exercises.ipynb) and acquire.py. The notebook will contain all your work as you move through the exercises. The acquire.py file should contain the final functions.



In [6]:
# imports

import pandas as pd
import numpy as np
import os

# visualize
import seaborn as sns
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(11, 9))
plt.rc('font', size=13)

# turn off pink warning boxes
# import warnings
# warnings.filterwarnings("ignore")

# acquire
from env import host, user, password
from pydataset import data
import acquire

1. In a jupyter notebook, classification_exercises.ipynb, use a python module (pydata or seaborn datasets) containing datasets as a source from the iris data. Create a pandas dataframe, df_iris, from this data.

In [14]:
# Create sql query and save to variable.

sql_query = 'SELECT * FROM measurements'

In [15]:
# Create connection url and save to a variable.

connection_url = f'mysql+pymysql://{user}:{password}@{host}/iris_db'

In [17]:

# Use my variables in the pandas read_sql() function.

df_iris = pd.read_sql(sql_query, connection_url)
df_iris.head(3)

measurement_id  sepal_length  sepal_width  petal_length  petal_width  \
0               1           5.1          3.5           1.4          0.2   
1               2           4.9          3.0           1.4          0.2   
2               3           4.7          3.2           1.3          0.2   

   species_id  
0           1  
1           1  
2           1

1a. print the first 3 rows


In [19]:
df_iris.head(3)

measurement_id  sepal_length  sepal_width  petal_length  petal_width  \
0               1           5.1          3.5           1.4          0.2   
1               2           4.9          3.0           1.4          0.2   
2               3           4.7          3.2           1.3          0.2   

   species_id  
0           1  
1           1  
2           1

1b. print the number of rows and columns (shape)

In [21]:
df_iris.shape

(150, 6)

1c. print the column names

In [23]:
df_iris.columns

Index(['measurement_id', 'sepal_length', 'sepal_width', 'petal_length',
       'petal_width', 'species_id'],
      dtype='object')

1d. print the data type of each column

In [24]:
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   measurement_id  150 non-null    int64  
 1   sepal_length    150 non-null    float64
 2   sepal_width     150 non-null    float64
 3   petal_length    150 non-null    float64
 4   petal_width     150 non-null    float64
 5   species_id      150 non-null    int64  
dtypes: float64(4), int64(2)
memory usage: 7.2 KB


1e. print the summary statistics for each of the numeric variables. Would you recommend rescaling the data based on these statistics?

In [25]:
df_iris.describe()

measurement_id  sepal_length  sepal_width  petal_length  petal_width  \
count      150.000000    150.000000   150.000000    150.000000   150.000000   
mean        75.500000      5.843333     3.057333      3.758000     1.199333   
std         43.445368      0.828066     0.435866      1.765298     0.762238   
min          1.000000      4.300000     2.000000      1.000000     0.100000   
25%         38.250000      5.100000     2.800000      1.600000     0.300000   
50%         75.500000      5.800000     3.000000      4.350000     1.300000   
75%        112.750000      6.400000     3.300000      5.100000     1.800000   
max        150.000000      7.900000     4.400000      6.900000     2.500000   

       species_id  
count  150.000000  
mean     2.000000  
std      0.819232  
min      1.000000  
25%      1.000000  
50%      2.000000  
75%      3.000000  
max      3.000000

In [26]:
# I would recommend rounding down to 4 decimal places to make it easier to read / manipulate

2. Read the Table1_CustDetails table from the Excel_Exercises.xlsx file into a dataframe named df_excel.

In [28]:
# getting this set up

df_excel = pd.read_excel('Excel_Exercises.xlsx', sheet_name='Table1_CustDetails')
df_excel.head(3)

customer_id  gender  is_senior_citizen partner dependents  phone_service  \
0  0002-ORFBO  Female                  0     Yes        Yes              1   
1  0003-MKNFE    Male                  0      No         No              2   
2  0004-TLHLJ    Male                  0      No         No              1   

   internet_service  contract_type      payment_type  monthly_charges  \
0                 1              1      Mailed check             65.6   
1                 1              0      Mailed check             59.9   
2                 2              0  Electronic check             73.9   

   total_charges churn  
0         593.30    No  
1         542.40    No  
2         280.85   Yes

2a. assign the first 100 rows to a new dataframe, df_excel_sample

In [29]:
df_excel_sample = df_excel.head(100)

In [31]:
# checking my work...
df_excel_sample.shape

(100, 12)

2b. print the number of rows of your original dataframe

In [34]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7049 entries, 0 to 7048
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   customer_id        7049 non-null   object 
 1   gender             7049 non-null   object 
 2   is_senior_citizen  7049 non-null   int64  
 3   partner            7049 non-null   object 
 4   dependents         7049 non-null   object 
 5   phone_service      7049 non-null   int64  
 6   internet_service   7049 non-null   int64  
 7   contract_type      7049 non-null   int64  
 8   payment_type       7049 non-null   object 
 9   monthly_charges    7049 non-null   float64
 10  total_charges      7038 non-null   float64
 11  churn              7049 non-null   object 
dtypes: float64(2), int64(4), object(6)
memory usage: 661.0+ KB


2c. print the first 5 column names

In [37]:
df_excel.columns[:5]

Index(['customer_id', 'gender', 'is_senior_citizen', 'partner', 'dependents'], dtype='object')

2d. print the column names that have a data type of object


In [48]:
df_excel.select_dtypes(['object']).columns

Index(['customer_id', 'gender', 'partner', 'dependents', 'payment_type',
       'churn'],
      dtype='object')

In [49]:
# what if I wanted multiple dtypes...
df_excel.select_dtypes(include=['object', 'bool']).columns

Index(['customer_id', 'gender', 'partner', 'dependents', 'payment_type',
       'churn'],
      dtype='object')

2e. compute the range for each of the numeric variables.


In [50]:
# give me a list of numeric columns
df_excel.select_dtypes(exclude=['object']).columns

Index(['is_senior_citizen', 'phone_service', 'internet_service',
       'contract_type', 'monthly_charges', 'total_charges'],
      dtype='object')

In [55]:
df_excel.select_dtypes(exclude='object').max() - df_excel.select_dtypes(exclude='object').min()

is_senior_citizen       1.0
phone_service           2.0
internet_service        2.0
contract_type           2.0
monthly_charges       100.5
total_charges        8666.0
dtype: float64

3. Read the data from this google sheet into a dataframe, df_google

In [56]:
sheet_url = 'https://docs.google.com/spreadsheets/d/1Uhtml8KY19LILuZsrDtlsHHDC9wuDGUSe8LTEwvdI5g/edit?usp=sharing'

In [60]:
csv_export_url = sheet_url.replace('/edit?usp=sharing', '/export?format=csv&gid=341089357')


In [61]:
df_google = pd.read_csv(csv_export_url)
df_google.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

3a. print the first 3 rows

In [62]:
df_google.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

3b. print the number of rows and columns

In [63]:
df_google.shape

(891, 12)

3c. print the column names

In [64]:
df_google.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

3d. print the data type of each column

In [66]:
df_google.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


3e. print the summary statistics for each of the numeric variables

In [67]:
df_google.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

3f. print the unique values for each of your categorical variables

In [68]:
df_google.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [75]:
# how to get number of unique entries per column/Series
df_google.filter(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked']).nunique()

Survived    2
Pclass      3
Sex         2
SibSp       7
Parch       7
Embarked    3
dtype: int64

In [80]:
df_google.filter(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked'])


Survived  Pclass     Sex  SibSp  Parch Embarked
0           0       3    male      1      0        S
1           1       1  female      1      0        C
2           1       3  female      0      0        S
3           1       1  female      1      0        S
4           0       3    male      0      0        S
..        ...     ...     ...    ...    ...      ...
886         0       2    male      0      0        S
887         1       1  female      0      0        S
888         0       3  female      1      2        S
889         1       1    male      0      0        C
890         0       3    male      0      0        Q

[891 rows x 6 columns]

In [88]:
cats_only_df = df_google.filter(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked'])
cats_only_df.head()

Survived  Pclass     Sex  SibSp  Parch Embarked
0         0       3    male      1      0        S
1         1       1  female      1      0        C
2         1       3  female      0      0        S
3         1       1  female      1      0        S
4         0       3    male      0      0        S

In [91]:
# Survived unique values...
cats_only_df['Survived'].unique()

array([0, 1])

In [93]:
# Pclass unique values
cats_only_df['Pclass'].unique()

array([3, 1, 2])

In [98]:
# Sex unique values
cats_only_df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [99]:
# SibSp unique values
cats_only_df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [100]:
# Parch unique values
cats_only_df['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [101]:
# Embarked unique values
cats_only_df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

Make a new python module, acquire.py to hold the following data aquisition functions:

1. Make a function named get_titanic_data that returns the titanic data from the codeup data science database as a pandas data frame. Obtain your data from the Codeup Data Science Database.

In [8]:
df_titantic = get_titantic_data()
df_titantic.head()

NameError: name 'get_titantic_data' is not defined

2. Make a function named get_iris_data that returns the data from the iris_db on the codeup data science database as a pandas data frame. The returned data frame should include the actual name of the species in addition to the species_ids. Obtain your data from the Codeup Data Science Database.

3. Once you've got your get_titanic_data and get_iris_data functions written, now it's time to add caching to them. To do this, edit the beginning of the function to check for a local filename like titanic.csv or iris.csv. If they exist, use the .csv file. If the file doesn't exist, then produce the SQL and pandas necessary to create a dataframe, then write the dataframe to a .csv file with the appropriate name.